<a href="https://colab.research.google.com/github/theclosedbook/PyTorch/blob/main/PyTorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.0.1+cu118


## Intro To Tensors

pytorch tensors are created using torch.tensors  = https://pytorch.org/docs/stable/tensors.html

In [2]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
#get tensor back as python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
#TENSOR
TENSOR = torch.tensor([[[[[[1,2,3],[4,5,6],[7,8,9],[10,11,12],[16,17,18]]]]]])
TENSOR

tensor([[[[[[ 1,  2,  3],
            [ 4,  5,  6],
            [ 7,  8,  9],
            [10, 11, 12],
            [16, 17, 18]]]]]])

In [13]:
TENSOR.ndim

6

In [14]:
TENSOR.shape

torch.Size([1, 1, 1, 1, 5, 3])

In [15]:
TENSOR[0,0]

tensor([[[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9],
          [10, 11, 12],
          [16, 17, 18]]]])

### Random Tensors
Why Random Tensors?
Random Tensors are important because the way many neural networks learn is that they start with tensors full of random numebrs and then adjust those random numbers to better represnt the data.

`Start with random numbers -> Look at data -> update random numbers -> look at the data -> update random numbers`


In [16]:
# Create a random tensor of size (3,4)
random_tensor =torch.rand(3,4)
random_tensor

tensor([[0.7171, 0.1418, 0.4000, 0.6611],
        [0.1600, 0.0961, 0.3279, 0.3296],
        [0.1281, 0.9039, 0.5041, 0.5016]])

In [17]:
random_tensor.ndim

2

In [18]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (224,224,3)) #height,width,color channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [19]:
# Create a tensor of all zeros
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
#Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

### Creating a range of tensors and tesnors-like


In [22]:
one_to_ten = torch.arange(start = 1, end = 11 , step =1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
# Create tensor like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**Note:** Tensor datatypes os one of the 3 big errors you'll run into with pytorch & Deep Learning.

1.Tensors not right data type

2.Tensor not right shape

3.Tensor not on right device

In [24]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None # What data type is tensor (eg float32 or float 16)
                               ,device=None # What device i.e what gpu it is using
                               ,requires_grad=False #To track the gradients with these tensors operations
                               )
float_32_tensor

tensor([3., 6., 9.])

In [25]:
float_32_tensor.dtype

torch.float32

In [26]:
float_16_tensors = float_32_tensor.type(torch.float16)
float_16_tensors

tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
float_16_tensors * float_32_tensor

tensor([ 9., 36., 81.])

In [28]:
int_32_tensor = torch.tensor([3,6,8],dtype = torch.int64)
int_32_tensor

tensor([3, 6, 8])

In [29]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 72.])

### Getting Information from Tensors

1.Tensors not right data type - to do get datatype from a tensor , can use `tensor.dtype`

2.Tensor not right shape - to get shape from a tensor , can use `tensor.shape`

3.Tensor not on right device- to get device from a tensor , can use `tensor.device`


In [30]:
#Create a tensor

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9330, 0.4806, 0.9906, 0.1625],
        [0.7669, 0.6310, 0.5174, 0.5188],
        [0.0245, 0.8601, 0.7818, 0.5537]])

In [31]:
print(some_tensor)
print(f"Data type of tensor :{some_tensor.dtype}")
print(f"Shape of the tensor :{some_tensor.shape}")
print(f"Device of the tensor:{some_tensor.device}")

tensor([[0.9330, 0.4806, 0.9906, 0.1625],
        [0.7669, 0.6310, 0.5174, 0.5188],
        [0.0245, 0.8601, 0.7818, 0.5537]])
Data type of tensor :torch.float32
Shape of the tensor :torch.Size([3, 4])
Device of the tensor:cpu


### Manipulating Tensors (Tensors Operations)

Tensor operations include:
*   Addition
*   Subtraction
*   Multiplication(element-wise)
*   Divison
*   Matrix Multipliaction




In [32]:
#Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [33]:
tensor * 10

tensor([10, 20, 30])

In [34]:
tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [35]:
tensor

tensor([1, 2, 3])

In [36]:
tensor - 10

tensor([-9, -8, -7])

In [37]:
#Try out PyTorch in-built functions
torch.mul(tensor , 10)

tensor([10, 20, 30])

In [38]:
torch.add(tensor , 10)

tensor([11, 12, 13])

In [39]:
torch.sub(tensor , 10)

tensor([-9, -8, -7])

In [40]:
torch.div(tensor , 10)

tensor([0.1000, 0.2000, 0.3000])

### Matrix Multiplications

Two main ways of performing multiplication in neural networks and Deep Learning:

* Element Wise Multiplication
* Matrix Multipliaction (Dot-Product)

There are two main rules Matrix Multiplicationb needs to satisfy
1. The **inner dimensions** must watch:
* `(3,2) @ (3,2)` wont work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of the **outer dimensions**
* `(2,3) @ (3,2) -> (2,2)`
* `(3,2) @ (2,3) ->(3,3)`

In [41]:
# Elemnt Wise Multipliaction

tensor * tensor

tensor([1, 4, 9])

In [42]:
print(tensor, "*",tensor )
print(f"Equals :{tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals :tensor([1, 4, 9])


In [43]:
#Matrix Multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [44]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 420 µs, sys: 0 ns, total: 420 µs
Wall time: 427 µs


In [45]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 35 µs, sys: 6 µs, total: 41 µs
Wall time: 43.4 µs


tensor(14)

### One of the most common error in DL: Shape Error

In [46]:
#Shapes for Matrix Multiplication
tensor_A = torch.tensor([[1,2],[3,4],[5,6]])
tensor_B = torch.tensor([[7,8],[9,10],[11,12]])

tensor_A.shape
#tensor_B.shape

torch.Size([3, 2])

To fix out tensor shape issues we can manipulate shape of one of our tensors using transpose

In [47]:
tensor_B.T.shape

torch.Size([2, 3])

In [48]:
# the matrix multiplication operation works when tensor_b is transposed

print(f"Original Shapes : tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New Shapes : tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match ")
print("Output\n")

output  = torch.matmul(tensor_A,tensor_B.T)
print(output)

print(f"\n Output shape: {output.shape}")





Original Shapes : tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New Shapes : tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match 
Output

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

 Output shape: torch.Size([3, 3])


## Finding the min,max,mean,sum etc (tensor aggregation)

In [49]:
#Create a Tensor
x=torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [50]:
#Finding the min
torch.min(x) , x.min()

(tensor(1), tensor(1))

In [51]:
#Finding the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [52]:
#Finding the mean - Note: torch .mean() funtion requires a tensor of float32 datatype
torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [53]:
#Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

In [54]:
x


tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [55]:
#Find the position in tensor that has the minimum value with argmin() -> returns index position of the target tenosr where the minimum value occurs
x.argmin()

tensor(0)

In [56]:
x[0]

tensor(1)

In [57]:
#Find the position in tenosr that has maximum value with argmax() -> returns index position of the target tensor where the maximum value occurs
x.argmax()

tensor(9)

In [58]:
x[9]

tensor(91)

#Reshaping , Stacking , Squeezing and Unsqueezing tensors
* reshaping - reshape an input tensor toa defined shape
* View - Return a view of an input tensor of a certain shape but keep the same memory as a original tensor
* Stacking - combine multiple tensors on top of each other (vtsack) or side bby side (hstack)
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way

In [59]:
#Lets create a tensor

x=torch.arange(1.,10,)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [60]:
x_reshaped = x.reshape(1,9)
x_reshaped , x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [61]:
#Change the view
z=x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [62]:
#Changing z changes x (because a view of a tensor shares the same memory as the original )

z[:, 0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [63]:
# Stack tensors on top of each other
x_stacked =torch.stack([x,x,x,x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [64]:
# torch.squeeze() - removes all single dimensions from a target tensor

print(f"Previous Tensor: {x_reshaped}")
print(f"Previous Shape:{x_reshaped.shape}")

#Remosve extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"New Tensor : {x_squeezed}")
print(f"New Tensor Shape:{x_squeezed.shape}")


Previous Tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous Shape:torch.Size([1, 9])
New Tensor : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New Tensor Shape:torch.Size([9])


In [65]:
# torch.unsqueeze() - adds a  single dimensions to a target tensor at a specefic dimension
print(f"Previous Target: {x_squeezed}")
print(f"Previous Shape:{x_squeezed.shape}")

#Add an extra dimension
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"New Tensor:{x_unsqueezed}")
print(f"New Shape :{x_unsqueezed.shape}")

Previous Target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous Shape:torch.Size([9])
New Tensor:tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New Shape :torch.Size([1, 9])


In [66]:
# torch.permute - reaaranges the dimensions  of a target tensor ion a specific order

x_original = torch.rand(size = (223,224,3))
# Permute the original tensor to re arrange the axis (or dim) order

x_permuted = x_original.permute(2,0,1) # shifts axis 0->1 , 1->2 , 2->0

print(f"Previosu Shape : {x_original.shape}")
print(f"New Shape:{x_permuted.shape}")

Previosu Shape : torch.Size([223, 224, 3])
New Shape:torch.Size([3, 223, 224])


## Indexing (Selecting Data from tensors )

Indexing with PyTorch is simmilar to indexing with Numpy

In [67]:
#Create a tensor

x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [68]:
#Lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [69]:
#Lets index on middle bracket (dim = 1)
x[0][0]

tensor([1, 2, 3])

In [70]:
#Lets index on most inner bracket (last dimension)
x[0][2][2]

tensor(9)

In [71]:
# Get all value sof 0 dimesion bur only 1 index value of 1st and 2nd dimension
x[:,:,2]

tensor([[3, 6, 9]])

In [72]:
#When convertiing from numpy -> pytorch , pytorch reflects numpys default datatype of float64 unless specefied otherwise
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [73]:
#change the value of  array
array = array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [74]:
#tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [75]:
#Change the tenosr , what vhappens to numpy_tensor
tensor = tensor + 1
tensor , numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Reproducbility (trying to take random out of random)

`start with random numbers -> tensor operations -> update random numbers to try abd make better representations of the data -> agin -> again -> again ->`

To reduce the randomness in NL and PyT cpmes a concept of a
**random seed**

Essentially what the random seed does is "fllavour" the randomness


In [76]:
#Create 2 random tensors
random_tensor_a = torch.rand(3,4)
random_tensor_b = torch.rand(3,4)

print(random_tensor_a)
print(random_tensor_b)

print(random_tensor_a == random_tensor_b)

tensor([[0.6951, 0.0654, 0.1360, 0.3433],
        [0.6456, 0.0872, 0.1471, 0.2086],
        [0.8470, 0.9545, 0.6529, 0.9191]])
tensor([[0.4073, 0.5191, 0.8628, 0.1951],
        [0.0789, 0.8120, 0.7156, 0.3332],
        [0.1149, 0.7566, 0.0247, 0.7329]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [77]:
#set the random seed

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_c = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)

random_tensor_d = torch.rand(3,4)

print(random_tensor_c)
print(random_tensor_d)

print(random_tensor_c == random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors objects and Pytorch objects on the GPU's (and making faster computations)

GPUs = faster coputations on numbers , thanks to CUDA + NVIDIA hardware + Pytorch working behind the scenes to make everything Hunky Dory


### 1. Getting a Gpu

1.Easiest - Use google colab for a gree GPU(options to upgrade as well)

2.Use your own GPU - takes a little bit of setup (investment)

3.Use cloud computing (GCP,AWS,Azure)

In [78]:
!nvidia-smi

Fri Sep 15 19:50:51 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   54C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### 2. Check for GPU access for PyTorch

In [79]:
#Check for GPU access with Python
import torch
torch.cuda.is_available()

True

In [80]:
#Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [81]:
#count number of devices
torch.cuda.device_count()

1

##Putting tensors and models on the gpu

the reason we want our tenors/models on the gpu because using a gpu results in faster computations

In [82]:
#cerate a tensor(default is on cpu)

tensor = torch.tensor([1,2,3],device = "cpu")
#tensor not on gpu

print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [83]:
#Move tensor to GPU

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensors back to CPU

In [85]:
#If tensor is on GPU cant tranform it into Numpy

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [86]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')